spring.application.name=car-dealership-api

server.address = 0.0.0.0
server.port = ${PORT:3000}

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.dialect=org.hibernate.dialect.MYSQL
spring.jpa.hibernate.ddl-auto=update


logging.level.org.springframework=ERROR
logging.level.org.apache.catalina=ERROR
logging.level.org.apache.coyote=ERROR
logging.level.org.springframework.boot.devtools=OFF
logging.level.web=OFF
logging.level.org.hibernate=off
logging.level.com.zaxxer.hikari=off


