package com.atharva.dealership.user;

import java.util.Optional;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import static org.mockito.ArgumentMatchers.any;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.security.crypto.password.PasswordEncoder;

import com.atharva.dealership.dto.RegisterUserRequest;
import com.atharva.dealership.exception.EmailAlreadyExistsError;
import com.atharva.dealership.exception.ValidationError;

/*
 * Assumed production API for the green step:
 *
 * Classes:
 * - UserService
 * - UserRepository, a Spring Data JPA repository for User
 * - User
 * - RegisterUserRequest
 *
 * Methods:
 * - UserService.registerUser(RegisterUserRequest request)
 * - UserService.register(RegisterUserRequest request)
 * - UserRepository.save(User user)
 * - UserRepository.create(User user)
 * - UserRepository.findByEmail(String email)
 * - PasswordEncoder.encode(String rawPassword)
 * - RegisterUserRequest.getEmail()
 * - RegisterUserRequest.getPassword()
 * - User.getEmail()
 * - User.getPassword()
 *
 * Constructors:
 * - RegisterUserRequest(String email, String password)
 *
 * Fields:
 * - User.id, autogenerated with @GeneratedValue
 * - RegisterUserRequest.email
 * - RegisterUserRequest.password
 * - User.email
 * - User.password
 *
 * Choice:
 * - This test assumes registerUser returns the persisted User entity. If the
 *   application later prefers a response DTO, replace the result type with that
 *   DTO and keep the assertion that the returned email matches the request.
 */
@ExtendWith(MockitoExtension.class)
class UserServiceTest {

    @Mock
    private UserRepository userRepository;

    @Mock
    private PasswordEncoder passwordEncoder;

    @InjectMocks
    private UserService userService;

    @Test
    void registerUserWithUniqueEmailAndValidPasswordEncodesPasswordBeforeSaving() {
        String email = "valid.user@example.com";
        String rawPassword = "StrongPassword123!";
        String encodedPassword = "$2a$10$encoded-password";
        RegisterUserRequest request = new RegisterUserRequest(email, rawPassword);

        when(passwordEncoder.encode(rawPassword)).thenReturn(encodedPassword);
        when(userRepository.save(any(User.class))).thenAnswer(invocation -> invocation.getArgument(0));

        User result = userService.registerUser(request);

        verify(passwordEncoder, times(1)).encode(rawPassword);

        ArgumentCaptor<User> userCaptor = ArgumentCaptor.forClass(User.class);
        verify(userRepository, times(1)).save(userCaptor.capture());

        User savedUser = userCaptor.getValue();
        assertEquals(encodedPassword, savedUser.getPassword());
        assertEquals(email, result.getEmail());
    }

    @Test
    void registerWithInvalidEmailThrowsValidationErrorAndDoesNotCreateUser() {
        RegisterUserRequest request = new RegisterUserRequest("not-an-email", "StrongPassword123!");

        assertThrows(ValidationError.class, () -> userService.register(request));

        verify(userRepository, times(0)).save(any(User.class));
    }

    @Test
    void registerWithShortPasswordThrowsValidationErrorAndDoesNotCreateUser() {
        RegisterUserRequest request = new RegisterUserRequest("valid.user@example.com", "short");

        assertThrows(ValidationError.class, () -> userService.register(request));

        verify(userRepository, times(0)).save(any(User.class));
    }

    @Test
    void registerWithExistingEmailThrowsEmailAlreadyExistsErrorAndDoesNotCreateUser() {
        String email = "existing.user@example.com";
        RegisterUserRequest request = new RegisterUserRequest(email, "StrongPassword123!");
        User existingUser = new User(email, "$2a$10$existing-password");
        when(userRepository.findByEmail(email)).thenReturn(Optional.of(existingUser));

        assertThrows(EmailAlreadyExistsError.class, () -> userService.register(request));

        verify(userRepository, times(0)).save(any(User.class));
    }

    @Test
    void registerNormalizesEmailBeforeCheckingForExistingUser() {
        String normalizedEmail = "test@example.com";
        RegisterUserRequest request = new RegisterUserRequest("Test@Example.com", "StrongPassword123!");
        User existingUser = new User(normalizedEmail, "$2a$10$existing-password");
        when(userRepository.findByEmail(normalizedEmail)).thenReturn(Optional.of(existingUser));

        assertThrows(EmailAlreadyExistsError.class, () -> userService.register(request));

        verify(userRepository, times(1)).findByEmail(normalizedEmail);
        verify(userRepository, times(0)).save(any(User.class));
    }

    @Test
    void registerSavesNormalizedEmailWhenEmailDoesNotConflict() {
        String rawEmail = "  New.User@Example.com  ";
        String normalizedEmail = "new.user@example.com";
        String rawPassword = "StrongPassword123!";
        String encodedPassword = "$2a$10$encoded-password";
        RegisterUserRequest request = new RegisterUserRequest(rawEmail, rawPassword);

        when(userRepository.findByEmail(normalizedEmail)).thenReturn(Optional.empty());
        when(passwordEncoder.encode(rawPassword)).thenReturn(encodedPassword);
        when(userRepository.save(any(User.class))).thenAnswer(invocation -> invocation.getArgument(0));

        userService.register(request);

        ArgumentCaptor<User> userCaptor = ArgumentCaptor.forClass(User.class);
        verify(userRepository, times(1)).save(userCaptor.capture());
        assertEquals(normalizedEmail, userCaptor.getValue().getEmail());
    }
}
